# Generated by Django 4.2.4 on 2023-08-17 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=250, null=True)),
                ('title', models.CharField(max_length=290, null=True)),
                ('description', models.TextField()),
                ('url', models.URLField(max_length=1000)),
                ('urlToImage', models.ImageField(upload_to='wall steat news ')),
                ('publishedAt', models.CharField(max_length=200)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NewsBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=250, null=True)),
                ('title', models.CharField(max_length=290, null=True)),
                ('description', models.TextField()),
                ('url', models.URLField(max_length=1000)),
                ('urlToImage', models.ImageField(upload_to='business_news Images')),
                ('publishedAt', models.CharField(max_length=200)),
                ('content', models.TextField()),
            ],
        ),
    ]
