# Generated by Django 4.2.4 on 2023-08-17 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='publishedAt',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='url',
            field=models.URLField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='urlToImage',
            field=models.ImageField(upload_to='business_news Images'),
        ),
        migrations.AlterField(
            model_name='newsbusiness',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='newsbusiness',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='newsbusiness',
            name='publishedAt',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newsbusiness',
            name='url',
            field=models.URLField(max_length=1000, null=True),
        ),
    ]
